spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <cliend id>
            client-secret: <client secret>
  data:
    cassandra:
      keyspace-name: main
      username: <client id>
      password: <client secret>
      schema-action: recreate_drop_unused
      request:
        timeout: 10s
      connection:
        connection-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: <id>
  region: <region>
  keyspace: <keyspace>
  application.token: <token>

datastax.astra:
  secure-connect-bundle: secure-connect.zip
